config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :contacts
  resources :projects
  resources :experiences
  resources :information, only: [:index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	#Validations form is not empty
  validates_presence_of :name, :message => "cant be blank"
  validates_presence_of :email,  :message => "cant be blank"
  validates_presence_of :message,  :message => "cant be blank"
  VALID_CAPTCHA_REGEX = /\Aw68hp\z/i
  validates :captcha, presence: true, format: {with: VALID_CAPTCHA_REGEX, message: "text did not match image text"}
end

app/models/experience.rb
class Experience < ApplicationRecord
  #Image support via CarrierWave gem
  mount_uploader :picture, ExperienceUploader

  # Default order is set by project's order_listed attribute 
  default_scope -> { order(order_listed: :asc) }

  # When a work experience entry is created or edited, the work experience entrys after it have their order_listed attribute incremented by 1
  def Experience.increment_order(experience_number, experience_id)
    Experience.where("order_listed >= ? AND id != ?", experience_number, experience_id).update_all("order_listed = order_listed + 1")
  end

  # When a work experience entry is deleted, the work experience entrys after it have their order_listed attribute decremnted by 1
  def Experience.decrement_order(experience_number, experience_id)
    Experience.where("order_listed > ? AND id != ?", experience_number, experience_id).update_all("order_listed = order_listed - 1")
  end
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  #Image support via CarrierWave gem
  mount_uploader :picture, ProjectUploader

  # A project's order_listed attribute entails were the project is on the order sequence when projects are displayed 
  # Default order is set by project's order_listed attribute 
  default_scope -> { order(order_listed: :asc) }

  # When project is created or edited, the projects after it have their order_listed attribute incremented by 1
  def Project.increment_order(project_number, project_id)
    Project.where("order_listed >= ? AND id != ?", project_number, project_id).update_all("order_listed = order_listed + 1")
  end

  # When a project is deleted, the projects after it have their order_listed attribute decremnted by 1
  def Project.decrement_order(project_number, project_id)
    Project.where("order_listed > ? AND id != ?", project_number, project_id).update_all("order_listed = order_listed - 1")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["ADMIN"] && password == ENV["PASSWORD"]
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate, only: [:index, :destroy]
  
  def index
    @contacts = Contact.all
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_message(@contact).deliver_now
  		flash[:success] = "I have received your message. I will be in touch with you soon."
      redirect_to "/#contact"
    else
      @slash = "/"
      render :new
    end
  end

  def destroy
    Contact.find(params[:id]).destroy
    redirect_to contacts_url
  end

private

  def contact_params
    params.require(:contact).permit(:name, :email, :message, :captcha)
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :authenticate

  def index
    @experiences = Experience.all

    # I can edit and delete work experience entries from this controller with @edit_button = true
    @edit_button = true
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    if @experience.save
      Experience.increment_order(@experience.order_listed, @experience.id)
      redirect_to experiences_url 
    else
      render :new
    end

  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    @experience = Experience.find(params[:id])
    # Save order_listed attribute to update accoridingly later
    cache_order_listed = @experience.order_listed
    if @experience.update(experience_params)
      #Don't increment other order_listed attributes if order_listed is the same on the one being updated
      if cache_order_listed != @experience.order_listed
        Experience.increment_order(@experience.order_listed, @experience.id)
      end
      redirect_to experiences_url 
    else
      render :edit
    end
  end

  def destroy
    @experience = Experience.find(params[:id])
    Experience.decrement_order(@experience.order_listed, @experience.id)
    @experience.destroy
    redirect_to experiences_url
  end

private

  def experience_params
    params.require(:experience).permit(:name, :link, :position, :description, :date, :picture, :order_listed)
  end

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :authenticate
  def index
  	@information = Information.first
  end

  def edit
  	@information = Information.first
  end

  def update
  	@information = Information.first
  	if @information.update(information_params)
  		redirect_to information_index_path
  	else
  		render :edit
  	end
  end

private

  def information_params
    params.require(:information).permit(:headline, :about_myself, :development_experience, :interests, :github, :linkedin, :facebook, :instagram, :resume_link)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  	@information = Information.first
  	@client_work = Project.where(project_type: 'Client Work')
    @projects = Project.where.not(project_type: 'Client Work')
  	@experiences = Experience.all
  	@contact = Contact.new

  	#Counter is used to add a row div every 3 projects
  	@counter = 0
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate

  def index
  	@client_work = Project.where(project_type: 'Client Work')
    @projects = Project.where.not(project_type: 'Client Work')

    # I can edit and delete projects from this controller with @edit_button = true
    @edit_button = true

    #Counter is used to add a row div every 3 projects
    @counter = 0
  end

  def new
  	@project = Project.new
  end

  def create
  	@project = Project.new(project_params)
  	if @project.save
      Project.increment_order(@project.order_listed, @project.id)
      redirect_to projects_url 
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    # Save order_listed attribute to update accoridingly later
    cache_order_listed = @project.order_listed
    if @project.update(project_params)
      # Don't increment other order_listed attributes if order_listed is the same on the one being updated
      if cache_order_listed != @project.order_listed
        Project.increment_order(@project.order_listed, @project.id)
      end
      redirect_to projects_url 
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    Project.decrement_order(@project.order_listed, @project.id)
    @project.destroy
    redirect_to projects_url
  end

private

  def project_params
    params.require(:project).permit(:name, :description, :project_type, :website, :github, :documentation, :order_listed, :picture, :tools)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contacts/index.html.erb
<%= link_to "Back to Homepage", :root %>
  <div class="container" id="messages" align="center">
    <div class="row">
      <h1><u>All Messages</u></h1>
    </div>
    <div class="row">
      <div class="col-lg-2 col-md-2">Name</div>
      <div class="col-lg-2 col-md-2">Email</div>
      <div class="col-lg-4 col-md-4">Message</div>
      <div class="col-lg-2 col-md-2">Date</div>
      <div class="col-lg-2 col-md-2">Delete</div>
    </div>
    <hr>
    <% @contacts.each do |contact| %>
      <div class="row">
        <div class="col-lg-2 col-md-2"><%= contact.name %></div>
        <div class="col-lg-2 col-md-2"><%= contact.email %></div>
        <div class="col-lg-4 col-md-4"><%= contact.message %></div>
        <div class="col-lg-2 col-md-2"><%= contact.created_at.strftime("%B %d, %Y")%></div>
        <div class="col-lg-2 col-md-2"><%= link_to "Delete", contact, method: :delete, data: { confirm: "You sure?" } %></div>
      </div>
      <hr>
    <% end %>
  </div>

app/views/contacts/new.html.erb
<!-- ========== MENU ========== -->
<%= render partial: "shared/nav_menu" %>

  <!-- ========== CONTACT SECTION ========== -->
  <section name="contact">
    <div class="container">
      <div class="row">
        <h3><u>CONTACT ME</u></h3>
        <div class="col-lg-6 col-lg-offset-3">
          <%= render partial: "shared/contact_form" %>
        </div>
      </div>
    </div>
  </section>

app/views/experiences/_experience.html.erb
<div class="work-experience-entry">
            <% if @edit_button %>
              <%= link_to "Edit (Order: #{experience.order_listed})", edit_experience_url(experience.id), class: "btn btn-danger btn-lg" %>
              <%= link_to "Delete", experience, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-lg" %>
            <% end %>
            <h3 class="work-experience-title"><a href="<%= experience.link %>" target="_blank"><%= experience.name %> 
              <span class="work-experience-link">(
              <% if experience.link.include?("www.") %>
                <%= experience.link.split("www.")[1].capitalize %>
              <% else%>
                <%= experience.link.split("//")[1].capitalize %>
              <% end %>
              )</span></a></h3>
              <h4 class="work-experience-position col-sm-6"><%= experience.position %></h4> 
              <h4 class="work-experience-date col-sm-6"><%= experience.date %></h4>
            <ul>
              <li>
                <div class="work-experience-desc">
                  <figure>
                    <a href="<%= experience.link %>" target="_blank"><img src="<%= experience.picture.url %>" class="img-responsive" alt="<%= experience.name %>"></a>
                  </figure>
                  <div>
                    <ul class="work-exprience-points">
                      <% experience.description.split(",").each do |point| %>
                        <li><%= point %></li>   
                      <% end %>  
                    </ul>
                  </div>
                </div>
              </li>
            </ul>
          </div>  

app/views/experiences/_experience_form.html.erb
<%= form_for @experience do |f| %>
  <div class="row control-group">
    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
      <%= f.label :picture, value: "Image" %>
      <%= f.file_field :picture %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
      <%= f.label :name %>
      <%= f.text_field :name, :type => "text", :class => "form-control", :placeholder => "Name", :id => "name", :required => true %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
      <%= f.label :link %>
      <%= f.text_field :link, :type => "text", :class => "form-control", :placeholder => "Link", :id => "link", :required => true %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
      <%= f.label :position %>
      <%= f.text_field :position, :type => "text", :class => "form-control", :placeholder => "Position", :id => "position", :required => true %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
      <%= f.label :description %>
      <%= f.text_area :description, :rows => "5", :class => "form-control", :placeholder => "Description", :id => "description", :required => true %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
      <%= f.label :date %>
      <%= f.text_field :date, :type => "text", :class => "form-control", :placeholder => "Date: (from - end)", :id => "date", :required => true %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
      <%= f.label :order_listed %>
      <%= f.text_field :order_listed, :type => "text", :class => "form-control", :placeholder => "Order to be listed", :id => "order_listed", :required => true %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-8 col-xs-offset-2">
      <%= f.submit "Submit", :type => "submit", :class => "btn btn-danger btn-lg" %>
    </div>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Go Back", experiences_url %>
    <h3><u>Edit Experience</u></h3><br>
    <%= render partial: "experience_form" %>
  </div>
</div>

app/views/experiences/index.html.erb
<section name="work-experience" id="work-experience" class="latest-articles has-padding alternate-bg" >
  <div id="work-experience-layout">
		<div class="container">
			<div class="row row-padded">
				<div class="col-md-12">
          <%= link_to "Home", root_url %> | <%= link_to "New Work Experience", new_experience_url%>
          <h3>WORK EXPERIENCE</h3>
          <p class="centered"><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i></p>
          <%= render @experiences %>   
        </div>
      </div>
    </div>
  </div>
</section>

app/views/experiences/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Go Back", experiences_url %>
    <h3><u>New Experience</u></h3><br>
    <%= render partial: "experience_form" %>
  </div>
</div>

app/views/information/edit.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Go Back", information_index_path %>
    <h3><u>Edit Information</u></h3><br>
    <%= form_for @information do |f| %>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :headline %>
		      <%= f.text_field :headline, :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :about_myself, 'About Myself' %>
		      <%= f.text_area :about_myself, :rows => "5", :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :development_experience, 'Development Experience' %>
		      <%= f.text_area :development_experience, :rows => "5", :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :interests, 'Interests' %>
		      <%= f.text_area :interests, :rows => "5", :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :github %>
		      <%= f.text_field :github, :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :linkedin %>
		      <%= f.text_field :linkedin, :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :facebook %>
		      <%= f.text_field :facebook, :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :instagram %>
		      <%= f.text_field :instagram, :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row control-group">
		    <div class="form-group col-xs-8 col-xs-offset-2 floating-label-form-group controls">
		      <%= f.label :resume_link %>
		      <%= f.text_field :resume_link, :type => "text", :class => "form-control", :required => true %>
		    </div>
		  </div>
		  <div class="row">
		    <div class="form-group col-xs-8 col-xs-offset-2">
		      <%= f.submit "Submit", :type => "submit", :class => "btn btn-danger btn-lg" %>
		    </div>
		  </div>
		<% end %>
  </div>
</div>

app/views/information/index.html.erb
<div class="container">
	<div class="row text-left">
		<%= link_to "Home", root_url %> | <%= link_to "Edit Information", edit_information_path(1) %>
		<h1 class="text-center">Information</h1>
		<h3>Headline: <%= @information.headline %></h3>
		<h3>About Myself: <%= @information.about_myself %></h3> 
		<h3>Development Experience: <%= @information.development_experience %></h3> 
		<h3>Interests: <%= @information.interests %></h3> 
		<h3>Github: <%= @information.github %></h3> 
		<h3>Linkedin: <%= @information.linkedin %></h3> 
		<h3>Facebook: <%= @information.facebook %></h3> 
		<h3>Instagram: <%= @information.instagram %></h3> 
		<h3>Resume Link: <%= @information.resume_link %></h3> 
	</div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Eric Gonzalez</title>

  <!-- Favicon -->
  <%= favicon_link_tag 'favicon.ico' %>

  <!-- Meta Tags -->
  <meta charset="UTF-8">
  <meta name="description" content="Eric Gonzalez Personal Website">
  <meta name="author" content="Eric Gonzalez">  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>

  <!-- Stylesheets -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/particles.js/2.0.0/particles.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Fonts -->
  <link href='//fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125223151-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-125223151-1');
  </script>
</head>
<body data-spy="scroll" data-offset="0" data-target="#theMenu">
  <%= yield %>
</body>

<!-- Javascript -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/pages/index.html.erb
  <!-- ========== MENU ========== -->
  <%= render partial: "shared/nav_menu" %>


  <!-- ========== HEADER SECTION ========== -->
  <section id="home">
    <div id="headerwrap">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h1>Eric Gonzalez</h1>
            <h3><b><%= @information.headline %></b></h3><br><br>
            <a href="#about" class="smoothScroll"><%= image_tag "profile.jpg", :class => "img-circle" %></a>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- ========== ABOUT SECTION ========== -->
  <div id="particles_about"></div>
  <section id="about">
    <div class="container">
      <div class="row">
        <h2>ABOUT ME</h2>
        <p class="centered"><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i></p>
        <div class="col-lg-10 col-lg-offset-1">
          <h3 class="sub-title">Myself</h3>
          <p class="align-left"><%= @information.about_myself %> Feel free to check out my <a href="<%= @information.resume_link %>"" target="_blank">resume</a>.</p>

          <h3 class="sub-title">Development Experience</h3>
          <%= image_tag "tech-logos/rails.svg", class: "tech-logo" %>
          <%= image_tag "tech-logos/react.svg", class: "tech-logo" %>
          <%= image_tag "tech-logos/javascript.svg", class: "tech-logo" %>
          <%= image_tag "tech-logos/database.svg", class: "tech-logo" %>
          <%= image_tag "tech-logos/git.svg", class: "tech-logo" %>
          <div class="hero__terminal">
            <pre>
              <code class="shell-session demo"><span class="term_snip">eric_dev ~ $ </span></code>
            </pre>
          </div>

          <h3 class="sub-title">Interests</h3>
          <p class="align-left"><%= @information.interests %></p>
        </div>                
      </div>
    </div>
  </section>


  <!-- ========== WORK EXPERIENCE SECTION ========== -->
  <section id="work-experience" class="latest-articles has-padding alternate-bg">
    <div id="work-experience-layout">
      <div class="container">
        <div class="row row-padded">
          <div class="col-md-12">
            <h2>WORK EXPERIENCE</h2>
            <p class="centered"><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i></p>
            <%= render @experiences %>   
          </div>
        </div>
      </div>
    </div>
  </section>
  

  <!-- ========== PORTFOLIO SECTION ========== -->  
  <section id="portfolio" class="latest-articles has-padding alternate-bg">
    <div class="container text-center">
      <h2>PORTFOLIO</h2>
      <p class="centered"><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i></p>
      <div class="row">
        <h3>Client Work</h3>
        <hr style="width: 300px; margin-left: auto; margin-right: auto;">
        <%= render @client_work %>
      </div>
      <div class="row" style="margin-top: 90px;">
        <h3>Personal and Group Projects</h3>
        <hr style="width: 300px; margin-left: auto; margin-right: auto;">
        <% @counter = 0 %>
        <%= render @projects %>
      </div>
    </div>
  </section>


  <!-- ========== CONTACT SECTION ========== -->
  <div id="particles_contact"></div>
  <section id="contact">
    <div class="container">
      <div class="row">
        <h2>CONTACT ME</h2>
        <p class="centered"><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i></p>
        <div class="col-lg-6 col-lg-offset-3">
          <p>Feel free to contact me through any of the methods listed below. Also, don't forget to check out my <a href="<%= @information.resume_link %>" target="_blank">resume</a>.</p>
          <p>Email: <a href="mailto:contact@eric-gonzalez.com">contact@eric-gonzalez.com</a></p>
          <nav id="social">
            <ul class="social-buttons">
              <li><a title = "Github" href="<%= @information.github %>" target="_blank"><i class="fa fa-github" id = "githubcircle"></i></a></li>
              <li><a title = "Linked In" href="<%= @information.linkedin %>" target="_blank"><i class="fa fa-linkedin" id = "linkedincircle"></i></a></li>
              <li><a title = "Facebook" href="<%= @information.facebook %>" target="_blank"><i class="fa fa-facebook" id = "facebookcircle"></i></a></li>
              <li><a title = "Instagram" href="<%= @information.instagram %>" target="_blank"><i class="fa fa-instagram" id = "instagramcircle"></i></a></li>
            </ul>
          </nav>
          <p>You can also leave me a message here:</p>
          <%= render partial: "shared/contact_form" %>
        </div>
      </div>
    </div>
  </section>


  <!-- ========== FOOTER ========== -->
  <nav id="footer">
    <div class="container">
      <div class="pull-left fnav">
        <p>Copyright © Eric Gonzalez, All Rights Reserved</p>
      </div>
    </div>
  </nav>

app/views/projects/_project.html.erb
<% if @counter % 3 == 0 && @counter != 0%>
  </div>
  <div class="row">
<% end %>    
    <div class="col-md-4">
      <article class="article-post">
        <a href="<%= project.website %>" target="_blank">
          <div class="article-image has-overlay" style="background-image: url(<%= project.picture.url %>)">
            <span class="featured-tag"><%= project.project_type %></span>
          </div>
        </a>
        <figure>
          <figcaption>
            <h2 class="project-name"><%= project.name %></h2>
            <h4 class="project-tools">(<%= project.tools %>)</h4>
            <p><%= project.description %></p>
          </figcaption>
        </figure>
        <% if @edit_button %>
          <%= link_to "Edit (Order: #{project.order_listed})", edit_project_url(project.id), class: "btn btn-danger btn-lg" %>
          <%= link_to "Delete", project, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-lg" %>
        <% else %>
          <% if project.website.include?("drive.google") %>
            <%= link_to "Download", project.website, target: "blank", class: "btn btn-danger btn-lg" %>
          <% else %>
            <%= link_to "Visit Website", project.website, target: "blank", class: "btn btn-danger btn-lg" %>
          <% end %>

          <% unless project.project_type.eql?('Client Work')%>
            <%= link_to "Source Code", project.github, target: "blank", class: "btn btn-danger btn-lg" %>
          <% end %>
          
          <% if !project.documentation.nil? && !project.documentation.blank? %>
            <%= link_to "View Documentation", project.documentation, target: "blank", class: "btn btn-danger btn-lg doc" %>
          <% end %>
        <% end %>
      </article>
    </div>
<% @counter = @counter + 1 %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Go Back", projects_url %>
    <h3><u>Edit Project</u></h3><br>
    <%= render partial: "project_form" %>
  </div>
</div>

app/views/projects/index.html.erb
<section name="portfolio" class="latest-articles has-padding alternate-bg" >
  <div class="container text-center">
    <%= link_to "Home", root_url %> | <%= link_to "New Project", new_project_url %>
    <h3>PORTFOLIO</h3>
    <p class="centered"><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i></p>
    <div class="row">
      <h4>Client Work</h4>
      <hr style="width: 300px; margin-left: auto; margin-right: auto;">
      <%= render @client_work %>
    </div>
    <div class="row" style="margin-top: 90px;">
      <h4>Personal and Group Projects</h4>
      <hr style="width: 300px; margin-left: auto; margin-right: auto;">
      <% @counter = 0 %>
      <%= render @projects %>
    </div>
  </div>
</section>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Go Back", projects_url %>
    <h3><u>New Project</u></h3><br>
    <%= render partial: "project_form" %>
  </div>
</div>